name: Conditional Build Projects

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Conditional Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # Detect changes
      - name: Detect changed directories
        id: changes
        run: |
          # Check for changes in each project directory
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/menu-client/'; then
            echo "menu-client=true" >> $GITHUB_ENV
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^src/menu-cms/'; then
            echo "menu-cms=true" >> $GITHUB_ENV
          fi

      # Conditionally build menu-client
      - name: Build menu-client
        if: env.menu-client == 'true'
        working-directory: src/menu-client
        run: |
          yarn install
          yarn build

      # Conditionally build menu-cms
      - name: Build menu-cms
        if: env.menu-cms == 'true'
        working-directory: src/menu-cms
        run: |
          yarn install
          yarn build
